-- MySQL Script generated by MySQL Workbench
-- Fri Oct 17 09:39:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca6162m
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca6162m
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca6162m` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca6162m` ;

-- -----------------------------------------------------
-- Table `biblioteca6162m`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca6162m`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` CHAR(11) NULL,
  `telefone_cliente` VARCHAR(20) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `endereco_cliente` VARCHAR(100) NULL,
  `dt_nasc_cliente` DATE NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca6162m`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca6162m`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `email_funcionario` VARCHAR(100) NULL,
  `telefone_funcionario` VARCHAR(20) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca6162m`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca6162m`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca6162m`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca6162m`.`livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `nome_livro` VARCHAR(45) NOT NULL,
  `genero_livro` VARCHAR(45) NULL,
  `ano_livro` YEAR NULL,
  `autor_id_autor` INT NOT NULL,
  PRIMARY KEY (`id_livro`, `autor_id_autor`),
  INDEX `fk_livro_autor1_idx` (`autor_id_autor` ASC) ,
  CONSTRAINT `fk_livro_autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `biblioteca6162m`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca6162m`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca6162m`.`emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_emprestimo` DATE NOT NULL,
  `data_final_emprestimo` DATE NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `livro_id_livro` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`, `cliente_id_cliente`, `funcionario_id_funcionario`, `livro_id_livro`),
  INDEX `fk_emprestimo_cliente_idx` (`cliente_id_cliente` ASC) ,
  INDEX `fk_emprestimo_funcionario1_idx` (`funcionario_id_funcionario` ASC) ,
  INDEX `fk_emprestimo_livro1_idx` (`livro_id_livro` ASC) ,
  CONSTRAINT `fk_emprestimo_cliente`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `biblioteca6162m`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `biblioteca6162m`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`livro_id_livro`)
    REFERENCES `biblioteca6162m`.`livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
